name = "ltpt-exercise-programming-app"
main = "worker/index.js"
compatibility_date = "2025-11-10"

[[d1_databases]]
binding = "DB"
database_name = "ltpt-v3-db"
database_id = "44141afa-f791-448b-8ab0-350b47ce2307"

[[kv_namespaces]]
binding = "LTPT_V3_CACHE"
id = "7f4040050bf14d51b546919198e61fa9"
